# NumPy

70 NumPy exercises from machinelearning+

In [1]:
# 1. 버전 확인
import numpy as np
print(np.__version__)

1.21.6


In [2]:
# 2. 1차원 배열 선언 (0 ~ 9)
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 3. 3*3 True array 선언
# arr_bool = np.ones((3,3), dtype=bool)
arr_bool = np.full((3, 3), True, dtype=bool)
print(arr_bool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
# 4. 0 ~ 9 로 채워진 1차원 배열에서 홀수만 출력
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [5]:
# 5. 0 ~ 9 로 채워진 1차원 배열에서 홀수를 -1로 대체
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
# 6. 원래 배열에 영향을 주지 않고 다른 배열 대체
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr,'\n',out)

[0 1 2 3 4 5 6 7 8 9] 
 [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [7]:
# 7. 1차원 배열을 2차원 배열로 재구성
arr.reshape(2, -1) # -1로 설정하면 자동으로 열의 수를 결정

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# 8. 2개의 배열을 수직으로 쌓기
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

arr1 = np.concatenate([a, b], axis=0) # 방법 1
arr2 = np.vstack([a, b]) # 방법 2
arr3 = np.r_[a, b] # 방법 3
print(arr1,'\n','\n',arr2,'\n','\n',arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]] 
 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]] 
 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
# 9. 2개의 배열을 수평으로 쌓기
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
arr1 = np.concatenate([a, b], axis=1)
arr2 = np.hstack([a, b])
arr3 = np.c_[a, b]
print(arr1,'\n','\n',arr2,'\n','\n',arr3)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]] 
 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]] 
 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [10]:
# 10. 배열 활용
a = np.array([1, 2, 3])
b = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(b)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [11]:
# 11. 두 배열의 중복값을 추출
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

In [12]:
# 12. 중복값 제거 / From 'a' remove all of 'b'
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [13]:
# 13. 두 배열의 요소가 일치하는 위치
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [14]:
# 14. 배열에서 주어진 구간의 숫자를 추출
a = np.array([2, 6, 1, 9, 10, 3, 27])

index1 = np.where((a >= 5)&(a <= 10)) # 방법 1
print(index1)
print(a[index1])
index2 = np.where(np.logical_and(a >= 5, a <= 10)) # 방법 2
print(index2)
print(a[index2])
print(a[(a >= 5)&(a <= 10)]) # 방법 3

(array([1, 3, 4]),)
[ 6  9 10]
(array([1, 3, 4]),)
[ 6  9 10]
[ 6  9 10]


In [15]:
# 15. 스칼라 함수
def maxx(x, y):
  if x >= y:
    return x
  else:
    return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [16]:
# 16. 2차원 배열에서 두 개의 열 교환
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [17]:
# 17. 2차원 배열에서 두 개의 행 교환
arr = np.arange(9).reshape(3,3)
arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [18]:
# 18. 2차원 배열 행 거꾸로
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [19]:
# 19. 2차원 배열 열 거꾸로
arr = np.arange(9).reshape(3, 3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [20]:
# 20. 5에서 10 사이의 임의의 부동 소수점을 포함하는 2D 배열
rand_arr1 = np.random.randint(low=5, high=10, size=(5, 3)) + np.random.random((5, 3)) # 방법 1
print(rand_arr1)
rand_arr2 = np.random.uniform(5, 10, size=(5, 3))
print(rand_arr2)

[[8.99676309 9.74797179 9.99463002]
 [5.06435088 5.36772068 9.48931605]
 [8.35860271 7.28026898 8.8158369 ]
 [5.59347259 6.73090856 9.79557334]
 [7.71292545 7.10993583 5.641138  ]]
[[8.38156954 7.38534489 7.93253682]
 [9.19603301 7.47186819 6.77879647]
 [7.61972889 5.05208723 7.3226443 ]
 [9.52146639 5.2116648  8.11588851]
 [5.94999502 8.04248287 7.72594963]]


In [21]:
# 21. 소수점 이하 세 자리 출력
rand_arr = np.random.random([5, 3])
np.set_printoptions(precision=3)
print(rand_arr)

[[0.333 0.005 0.347]
 [0.503 0.435 0.31 ]
 [0.945 0.756 0.538]
 [0.84  0.831 0.603]
 [0.535 0.734 0.072]]


In [22]:
# 22. 과학적 표기법 표기 (예. 1e10)
np.set_printoptions(suppress=False) # print 옵션 초기화
np.random.seed(100)
rand_arr = np.random.random([3, 3])/1e3 # 1e3==1000
print(rand_arr)

np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [23]:
# 23. NumPy 출력 항목 수 제한
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [24]:
# 24. NumPy 출력 항목 수 제한 해제
# np.set_printoptions(threshold=np.nan)
# threshold=np.nan 지원을 의도한 적이 없으며 코드의 버그입니다.
import sys
np.set_printoptions(threshold=sys.maxsize)
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [25]:
# 25. iris 데이터 (url에서 텍스트를 그대로 유지하면서 숫자와 텍스트가 있는 데이터 세트를 가져오기)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [26]:
# 26. 1D 배열에서 특정 열 추출
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding=None)
#print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
print(species[:5])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [27]:
# 27. 1d 배열을 2d numpy 배열로 변환
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding=None)

iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d[:4],'\n')

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]] 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [28]:
# 28. NumPy 배열의 평균, 중앙값, 표준 편차 계산
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0], encoding=None)

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [29]:
# 29. 0 ~ 1 사이의 배열 정규화
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0], encoding=None)

Smax, Smin = sepallength.max(), sepallength.min()
# S = (sepallength - Smin)/(Smax - Smin) # 방법 1
S = (sepallength - Smin)/sepallength.ptp() # 방법 2
print(S)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

In [30]:
# 30. softmax 점수 계산
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object', encoding=None)
sepallength = np.array([float(row[0]) for row in iris])

def softmax(x):
  e_x = np.exp(x - np.max(x))
  return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

In [31]:
# 31. 백분위수
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0], encoding=None)

print(np.percentile(sepallength, q=[5, 95]))

[4.6   7.255]


In [32]:
# 32. 배열 임의의 위치에 값을 삽입
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object', encoding=None)

i, j = np.where(iris_2d)
np.random.seed(100) # 방법 1
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan
print(iris_2d[:10], '\n')

np.random.seed(100) # 방법 2
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']] 

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [33]:
# 33. NumPy 배열에서 결측치의 위치를 ​​찾기
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("결측치 개수: ", np.isnan(iris_2d[:, 0]).sum())
print("결측치 위치: ", np.where(np.isnan(iris_2d[:, 0])))

결측치 개수:  5
결측치 위치:  (array([ 38,  80, 106, 113, 121]),)


In [34]:
# 34. NumPy 배열 조건 2개 이상으로 필터링
# Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [35]:
# 35. 누락된 값이 포함된 행을 삭제
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3]])

In [36]:
# 36. NumPy 배열의 두 열 간의 상관 관계를 찾기
# iris 의 SepalLength(1열)와 PetalLength(3열)의 상관관계를 구하기
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(np.corrcoef(iris[:, 0], iris[:, 2])[0, 1])

0.8717541573048718


In [37]:
# 37. 배열에 null 값이 있는지 확인
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()

False

In [38]:
# 38. NumPy 배열에서 모든 누락된 값을 0으로 바꾸기
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:4], '\n')
iris_2d[np.isnan(iris_2d)] = 0
print(iris_2d[:4])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]] 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [39]:
# 39. NumPy 배열에서 고유한 값의 개수를 찾기
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
print(np.unique(species, return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([50, 50, 50]))


In [40]:
# 40. 숫자를 범주형(텍스트) 배열로 변환
# 3 미만 --> 'small' / 3-5 --> 'medium' / '>=5 --> 'large'
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

print(petal_length_cat[:4])

['small', 'small', 'small', 'small']


In [41]:
# 41. NumPy 배열의 기존 열에 새 열을 만들기
# iris_2d에 volume에 대한 새 열을 생성, 여기서 volume은 (pi x petallength x sepal_length^2)/3
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

volume = volume[:, np.newaxis]

out = np.hstack([iris_2d, volume])
print(out[:4])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa' 38.13265162927291]
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa' 35.200498485922445]
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa' 30.0723720777127]
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa' 33.238050274980004]]


In [42]:
# 42. 확률적 샘플링
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
# species 열 가져오기
species = iris[:, 4]
# 확률 생성
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
# 확률적 샘플링
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36]))


In [43]:
# 43. 다른 배열로 그룹화할 때 배열의 두 번째로 큰 값을 얻기
# setosa 종에서 petallength(꽃잎 길이)가 두번째로 긴 값
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
# 종과 꽃잎 길이 열 가져오기
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')
# 정렬 후 마지막에서 두번 째 값
print(np.unique(np.sort(petal_len_setosa))[-2])

1.7


In [44]:
# 44. 2D 배열을 열로 정렬하는 방법
# sepallength열을 기준으로 홍채 데이터셋을 정렬
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [45]:
# 45. numpy 배열에서 최빈값 찾기
# 홍채 데이터셋에서 꽃잎 길이(세 번째 열) 최빈값 찾기
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


In [46]:
# 46. ​​주어진 값보다 큰 값이 처음 나타나는 위치
# iris dataset의 4번째 열에 1.0보다 큰 값이 처음 나오는 위치를 찾기
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

print(np.argwhere(iris[:, 3].astype(float) > 1.0)[0])

[50]


In [47]:
# 47. 주어진 값보다 큰 값을 모두 바꾸기
# 배열 a에서 30보다 큰 값을 30으로, 10보다 작은 값을 10으로 모두 바꾸기
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

print(np.clip(a, a_min=10, a_max=30), '\n') # 방법 1
print(np.where(a < 10, 10, np.where(a > 30, 30, a))) # 방법 2

[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43] 

[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


In [48]:
# 48. numpy 배열에서 상위 값의 위치를 ​​얻기
# 주어진 배열에서 상위 5개 최대값의 위치를 ​​가져오기
np.random.seed(100)
a = np.random.uniform(1,50, 20)

print(a.argsort()[-5:]) # 방법 1
print(np.argpartition(-a, 5)[:5]) # 방법 2

[18  7  3 10 15]
[15 10  3  7 18]


In [49]:
# 49. 행 단위 계산
# 고유 값의 개수를 행 단위로 계산
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

def counts_of_all_values_rowwise(arr2d):
    # 고유값 및 행 개수
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # 행 별 모든 값 카운트
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

print(arr, '\n')
print(np.arange(1,11), '<- key')
counts_of_all_values_rowwise(arr)

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]] 

[ 1  2  3  4  5  6  7  8  9 10] <- key


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [50]:
# 50. 배열 합치기
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
array_of_arrays = np.array([arr1, arr2, arr3], dtype='object')
print('array_of_arrays: ', array_of_arrays)

arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


In [51]:
# 51. 배열에 대한 원-핫 인코딩 생성
# 원-핫 인코딩(배열의 각 고유 값에 대한 더미 이진 변수)을 계산
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
print(arr, '\n')

def one_hot_encodings(arr): # 방법 1
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

print(one_hot_encodings(arr))

print((arr[:, None] == np.unique(arr)).view(np.int8)) # 방법 1

[2 3 2 2 2 1] 

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [52]:
# 52. 범주형 변수로 그룹화된 행 번호를 만들기
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small,'\n')
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'] 

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


In [53]:
# 53. 주어진 범주형 변수를 기반으로 groud id를 생성
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small,'\n')
output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]
print(output)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'] 

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


In [54]:
# 54. 배열의 항목 순위를 지정
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)
print(a.argsort().argsort())

Array:  [ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]


In [55]:
# 55. 2차원 배열의 항목 순위를 지정
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [56]:
# 56. 2d 배열 각 행에서 최대값을 찾기
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a, '\n')
print(np.amax(a, axis=1)) # 방법 1
print(np.apply_along_axis(np.max, arr=a, axis=1)) # 방법 2

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]] 

[9 8 6 3 9]
[9 8 6 3 9]


In [57]:
# 57. 2d 배열의 각 행에 대해 최소값 / 최대값
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a, '\n')
print(np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]] 

[0.44 0.12 0.5  1.   0.11]


In [58]:
# 58. 중복 레코드를 찾기
np.random.seed(100)
a = np.random.randint(0, 5, 10)

# True값으로 이루어진 배열 생성
out = np.full(a.shape[0], True)

# 고유값의 인덱스 위치 찾기
unique_positions = np.unique(a, return_index=True)[1]

# 해당 위치에 False 넣기
out[unique_positions] = False
print(a)
print(out)

[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


In [59]:
# 59. 범주형 열로 그룹화된 숫자 열의 평균
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

# 방법 1
print([[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)])

# 방법 2
output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])
print(output)

[[b'Iris-setosa', 3.418], [b'Iris-versicolor', 2.7700000000000005], [b'Iris-virginica', 2.974]]
[[b'Iris-setosa', 3.418], [b'Iris-versicolor', 2.7700000000000005], [b'Iris-virginica', 2.974]]


In [60]:
# 60. PIL 이미지를 NumPy 배열로 변환
import io
from PIL import Image
import PIL, requests

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# 이미지 불러오기
I = Image.open(io.BytesIO(response.content))

# 사이즈 변환
I = I.resize([150,150])

# NumPy 배열로 변환
arr = np.asarray(I)
print(arr)

# NumPy 배열을 이미지로 변환
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

[[[  9  72 125]
  [ 10  73 126]
  [ 11  74 127]
  [ 10  73 126]
  [ 10  73 126]
  [ 10  73 126]
  [ 11  74 127]
  [ 14  76 130]
  [ 12  73 127]
  [ 13  74 128]
  [ 14  75 129]
  [ 14  75 129]
  [ 14  75 129]
  [ 14  76 128]
  [ 14  77 128]
  [ 12  75 126]
  [ 14  77 128]
  [ 14  77 128]
  [ 14  77 128]
  [ 15  78 129]
  [ 15  78 129]
  [ 15  78 131]
  [ 15  78 131]
  [ 15  78 131]
  [ 15  78 129]
  [ 14  77 127]
  [ 13  76 128]
  [ 14  77 131]
  [ 16  79 132]
  [ 16  79 132]
  [ 16  79 132]
  [ 16  79 132]
  [ 17  80 133]
  [ 17  80 133]
  [ 17  80 133]
  [ 17  80 133]
  [ 17  80 133]
  [ 16  79 132]
  [ 17  80 133]
  [ 18  81 134]
  [ 19  81 134]
  [ 20  84 133]
  [ 20  83 131]
  [ 21  83 132]
  [ 21  83 132]
  [ 22  82 132]
  [ 23  83 133]
  [ 24  84 134]
  [ 23  83 133]
  [ 25  85 135]
  [ 25  85 135]
  [ 25  85 135]
  [ 25  85 135]
  [ 26  86 136]
  [ 26  86 136]
  [ 26  86 136]
  [ 26  86 136]
  [ 28  88 138]
  [ 29  88 138]
  [ 31  89 139]
  [ 32  90 140]
  [ 30  88 138]
  [ 33  

In [61]:
# 61. NumPy 배열에서 누락된 값을 모두 삭제
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [62]:
# 62. 두 배열 사이의 유클리드 거리를 계산
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

dist = np.linalg.norm(a-b)
print(dist)

6.708203932499369


In [63]:
# 63. 1d 배열에서 모든 최고값을 찾기
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
print(peak_locations)

[2 5]


In [64]:
# 64. 2d 배열 각 행을 1d 배열의 값으로 빼기
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [65]:
# 65. 배열에서 항목의 n번째 인덱스 찾기
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

print([i for i, v in enumerate(x) if v == 1][n-1]) # 방법 1
print(np.where(x == 1)[0][n-1]) # 방법 2

8
8


In [66]:
# 66. NumPy의 datetime64객체를 datetime의 datetime객체로 변환
dt64 = np.datetime64('2022-05-01 16:50:10')

from datetime import datetime
print(dt64.tolist()) # 방법 1
print(dt64.astype(datetime)) # 방법 2

2022-05-01 16:50:10
2022-05-01 16:50:10


In [67]:
# 67. numpy 배열의 이동 평균을 계산
np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
  
print(moving_average(Z, n=3).round(2)) # 방법 1
print(np.convolve(Z, np.ones(3)/3, mode='valid')) # 방법 2

array:  [8 8 3 7 7 0 4 2 5 2]
[6.33 6.   5.67 4.67 3.67 2.   3.67 3.  ]
[6.33 6.   5.67 4.67 3.67 2.   3.67 3.  ]


In [68]:
# 68. 길이, 시작점, 단계 만 주고 배열 만들기
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

print(seq(start, length, step))

[ 5  8 11 14 17 20 23 26 29 32]


In [69]:
# 69. 누락된 날짜를 채우기
dates = np.arange(np.datetime64('2022-04-01'), np.datetime64('2022-04-25'), 2)
print(dates)

filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1) # 방법 1
output = np.hstack([filled_in, dates[-1]])
print(output)

out = [] # 방법 2
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))
filled_in = np.array(out).reshape(-1)
output = np.hstack([filled_in, dates[-1]])
print(output)

['2022-04-01' '2022-04-03' '2022-04-05' '2022-04-07' '2022-04-09'
 '2022-04-11' '2022-04-13' '2022-04-15' '2022-04-17' '2022-04-19'
 '2022-04-21' '2022-04-23']
['2022-04-01' '2022-04-02' '2022-04-03' '2022-04-04' '2022-04-05'
 '2022-04-06' '2022-04-07' '2022-04-08' '2022-04-09' '2022-04-10'
 '2022-04-11' '2022-04-12' '2022-04-13' '2022-04-14' '2022-04-15'
 '2022-04-16' '2022-04-17' '2022-04-18' '2022-04-19' '2022-04-20'
 '2022-04-21' '2022-04-22' '2022-04-23']
['2022-04-01' '2022-04-02' '2022-04-03' '2022-04-04' '2022-04-05'
 '2022-04-06' '2022-04-07' '2022-04-08' '2022-04-09' '2022-04-10'
 '2022-04-11' '2022-04-12' '2022-04-13' '2022-04-14' '2022-04-15'
 '2022-04-16' '2022-04-17' '2022-04-18' '2022-04-19' '2022-04-20'
 '2022-04-21' '2022-04-22' '2022-04-23']


In [70]:
# 70. 주어진 1D 배열에서 스트라이드를 생성
# 길이가 4이고 strides가 2
arr = np.arange(15) 

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
